<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="0" failures="1" skipped="0" tests="15" time="0.615" timestamp="2024-12-02T13:48:17.196717-03:00" hostname="DESKTOP-0D0VKIA"><testcase classname="test_calculadora" name="test_adicao" time="0.003" /><testcase classname="test_calculadora" name="test_subtracao" time="0.003" /><testcase classname="test_calculadora" name="test_multiplicacao" time="0.002" /><testcase classname="test_calculadora" name="test_divisao" time="0.001" /><testcase classname="test_user_manager" name="test_register_valid_user" time="0.003" /><testcase classname="test_user_manager" name="test_login_valid_user" time="0.002" /><testcase classname="test_user_manager" name="test_register_duplicate_email" time="0.004" /><testcase classname="test_user_manager" name="test_register_short_password" time="0.002" /><testcase classname="test_user_manager" name="test_register_password_without_number" time="0.010" /><testcase classname="test_user_manager" name="test_login_invalid_email" time="0.003" /><testcase classname="test_user_manager" name="test_login_invalid_password" time="0.007" /><testcase classname="test_user_manager" name="test_register_invalid_email_format" time="0.002"><failure message="Failed: DID NOT RAISE &lt;class 'ValueError'&gt;">user_manager = &lt;test_user_manager.UserManager object at 0x000002E1B23FE7E0&gt;

    def test_register_invalid_email_format(user_manager):
&gt;       with pytest.raises(ValueError, match="Formato de email inv√°lido."):
E       Failed: DID NOT RAISE &lt;class 'ValueError'&gt;

test_user_manager.py:85: Failed</failure></testcase><testcase classname="test_user_manager" name="test_register_valid_password_with_special_chars" time="0.007" /><testcase classname="test_user_manager" name="test_register_max_email_length" time="0.004" /><testcase classname="test_user_manager" name="test_concurrent_user_registration" time="0.012" /></testsuite></testsuites>